### ISSUE TITLE
Add Language Server to output

### ISSUE THREAD

**Issue by skbolton** [maximbaz/lightline-ale#16]
I am going to do some research on this because I think that this might need to be added to ALE, but I wanted to get a conversation started. I never really know if the language server is running or what the condition is. Would it be possible to configure this plugin to add Language Server health checks to its status?

**Comment by maximbaz** [comment]
Hi there, you did good by commenting on https://github.com/w0rp/ale/issues/1678, until ALE exposes this information there is really nothing that can be done in this project to add such an indicator. It seems that issue doesn't have much attention, I hope you'll be able to change that 😉 

I'm not using (n)vim anymore, but the idea is great and I support it, if ALE ever implements the API and you or someone else send a PR, I'll gladly merge it 👍

Because this issue is not actionable in any form right now, I'm going to close the ticket. But as I said, once the API is implemented, PRs are very welcome 😉

**Comment by skbolton** [comment]
Sounds good. I will poke you if I make any headway on it. Good to know you would consider it.
