### ISSUE TITLE
Show linting progress

### ISSUE THREAD

**Issue by damnskippy** [maximbaz/lightline-ale#2]
Per this [comment](https://github.com/w0rp/ale/issues/1363#issuecomment-368307402), `ale#engine#IsCheckingBuffer(buffer_number)` will return `1 `when ALE is busy checking a buffer, and `0 `otherwise.
I do currently use this as one of my personal/custom lightline components  i.e.something like this below.
```
function! Lightline_GetAleStatus()
    if ale#engine#IsCheckingBuffer(bufnr('%'))
        return 'ALE in progress'
    else
        return ''
endfunction
```
But perhaps this can be folded into this plugin via a 'linter_in_progress' component, with an hour glass icon as an indicator?
Just a suggestion/feature request.
Thanks.

**Comment by maximbaz** [comment]
This is an awesome idea, thanks for letting me know!

Personally I went for `spinner` icon, because hour glass seemed too "bold" for me, but as usual this is configurable so feel free to use any icon you like 🙂

![image](https://user-images.githubusercontent.com/1177900/36669416-2abb396e-1af5-11e8-85da-36d91528a26e.png)

![image](https://user-images.githubusercontent.com/1177900/36669408-2216b61c-1af5-11e8-8165-50105bb93171.png)

**Comment by damnskippy** [comment]
Great - thanks very much for considering.

**Comment by damnskippy** [comment]
For some reason I'm seeing the 'ok' component displayed as well while 'checking' component is active?
Am I missing something?

![capture](https://user-images.githubusercontent.com/5184519/36679900-635709f0-1ae2-11e8-893d-2959b1d16293.PNG)

**Comment by damnskippy** [comment]
A separate but somewhat related issue is that the OK component seems to be displayed unconditionally.
Or when filetypes when ALE is not used (linter not available for this filetype), or not applicable (`.txt` file for instance).
I don't know if this is possible without underlying support from ALE, but it would be great if 'ok' component is displayed only when linting has actually successfully been done with zero warnings and errors?  And not displayed if linting is not even done.  Or use a different indicator to say that linting is 'not applicable', for instance.  I can open a separate issue for this if you'd like.

**Comment by maximbaz** [comment]
Oh, nice catch - I'm not using "OK" component myself, that's why I didn't notice.

I quickly checked now, this naive fix doesn't really work:

```vim
function! lightline#ale#ok() abort
  if ale#engine#IsCheckingBuffer(bufnr(''))
    return ''
  " the rest of the code...
endfunction
```

I think it has something to do with autocommand, perhaps the event "linting is done" is being thrown while linting is still in progress and thus `IsCheckingBuffer` always returns true for OK component - but I'm not sure.

Actually, I like your last suggestion, we should not show OK indicator not only if linting is running, but also if it has not been performed at all. Please open the issue for that, and I think it will cover everything. But to tell the truth I don't know how to implement this...

**Comment by damnskippy** [comment]
Aw - that explains why you didn't run into this, and your proposed fix sounds good as well.
I'll open a separate issue regarding the 'ok' component.
Thanks!
