### ISSUE TITLE
Overlapping patched font with text

### ISSUE THREAD

**Issue by backpropper** [maximbaz/lightline-ale#21]
The patched font seems to overlap with text when the errors/warnings are in hundreds (more than 3 digits) 
<img width="362" alt="Screen Shot 2020-06-04 at 9 06 04 AM" src="https://user-images.githubusercontent.com/5422228/83712426-5fe3b680-a643-11ea-8623-78b2c5e9272b.png">

Can you also tell how to get the exact same appearance of the lightline as shown in the README screenshot?

**Comment by maximbaz** [comment]
> The patched font seems to overlap with text when the errors/warnings are in hundreds (more than 3 digits)

Sounds like your font declares wrong width for these characters, what I would recommend trying is to add some extra spaces after the icon, so e.g. `"\uf071 "` instead of `"\uf071"`. Would that work? I don't think there is something we can do otherwise on our side...

> Can you also tell how to get the exact same appearance of the lightline as shown in the README screenshot?

I'm not using neovim anymore, but here's the last state of my config before I removed it:

https://github.com/maximbaz/dotfiles/blob/2f1c6be73b66b41458cd802c9b125459c809c9fe/.config/nvim/init.vim

Not sure if it still works out of the box, but hopefully will give you some inspiration 🙂

**Comment by backpropper** [comment]
I see. Thanks for the info. Yeah adding a space is what I did as a workaround for now.
