### ISSUE TITLE
Questions on license

### ISSUE THREAD

**Issue by spywhere** [maximbaz/lightline-ale#22]
Hey! First of all, thanks for your plugin on integration between ALE and lightline, I have been using it for quite a long time now.

Now as I personally use neovim as my main vim editor, their LSP integration is quite good enough for my use case. So I'm seeking for an integration between native LSP from neovim with lightline. So far, I got nothing. Fortunately enough, neovim's documentations do have a section on how to get the information for that. And since I find your plugin's project structure to better suit the work I'm seeking, I have already start my project on these integration based on your work here so everyone else can reuse it.

So my version of the project for native LSP with lightline, so far I just have to change all function / variable names from `lightline#ale#...` to `lightline#lsp#...` and its implementation to a native LSP. And since everything is so perfect that I can just simply copy and update the name and its README, I wonder how should I credit you on this?

Let me know if you're happy if I can just simply clone and update your code to work with a new implementation and credit you. Otherwise, I can keep the work to myself.

**Comment by maximbaz** [comment]
Hey! Thanks for reaching out 🙂 

It has MIT license, which means you can do whatever you want - if you don't mind preserving the same license for your project, you can maybe just add your name next to mine, maybe leave a credit in README and that's it? 😉

Now that you mentioned it, let us actually switch to ISC license - it has exactly the same conditions, but is a bit more readable and user-friendly 🙂 I have already done it for a few other projects, I will commit this right away.

Super happy to see this being useful to you, good luck with your project! 🙂

**Comment by spywhere** [comment]
Sounds great, thanks for such a quick response.

**Comment by maximbaz** [comment]
Nicely done @spywhere! Just one nitpick since you asked about license ( 😉 ), you have accidentally copied the text of MIT license instead - you can also spot the difference, when you open [LICENSE in this project](https://github.com/maximbaz/lightline-ale/blob/master/LICENSE) you can see on top that Github itself renders `maximbaz/lightline-ale is licensed under the ISC License`, but when you open [LICENSE for lightline-lsp](https://github.com/spywhere/lightline-lsp/blob/master/LICENSE) Github doesn't seem to recognize it as a "standard" text - maybe it doesn't like the markdown-style link, I'm not sure... It's not as import, just found it curious and wanted to share 🙂

**Comment by spywhere** [comment]
Oh right! Nice cache. Let me fix it quickly then.
